### PR TITLE
Eager collections

### PR DESCRIPTION
**Pull request by kbsali**
- adds a note about EAGER doctrine configuration for automatically joining relations on sub-object serialization
- various updates/fixes/typos...

### CODE REVIEW

**Comment by Simperfit** [comment]
Thank you for the PR kbsali !

**Comment by dunglas** [comment]
Thank you very much for all these fixes @kbsali!

**Comment by kbsali** [comment]
has the site of the V1 doc been updated recently? I'm not seeing those changes online...

**Comment by dunglas** [comment]
No, I need to run an update.

**Comment by kbsali** [comment]
no problem, but i guess it can be frustrating for some contributors to not see their contributions 2+ months after it's been merged! ;)

**Comment by soyuka** [comment]
@kbsali not an issue, people using api-platform v2 are using github + markdown docs so they do see your updates ;)

**Comment by kbsali** [comment]
hmm... that's not the answer you should give really! V1 is probably still used by (many?) others, and if, when contributing, you don't get to see the changes you pushed published, chances are that contributor will not contribute again...

**Comment by soyuka** [comment]
Oh sorry thought you contributed on v2 docs and complained about it not being online! My bad.

**Comment by dunglas** [comment]
I fully agree it's my bad (only me can update the website). I'll do it when I'll be back in France. The real fix is to automate this process.

**Comment by teohhanhui** [comment]
Or use GitHub Pages...

**Comment by dunglas** [comment]
It uses github pages...

**Comment by soyuka** [comment]
We should merge pull requests directly on the gh-pages branch then.
Le lun. 8 août 2016 à 16:56, Kévin Dunglas <notifications@github.com> a
écrit :

**Pull request merged**
