### PR TITLE
Remove impolite language

### PR DESCRIPTION
**Pull request by teohhanhui**

### CODE REVIEW

**Comment by theofidry** [comment]
`dead simple`?

**Comment by teohhanhui** [comment]
http://english.stackexchange.com/questions/51410/dead-simple-vs-really-simple

**Comment by theofidry** [comment]
Yeah it's not formal either, but I don't feel like our target audience would feel offended by it. But if it's bothering you let's change it.

**Comment by dunglas** [comment]
Thank you @teohhanhui

**Pull request merged**
